### ISSUE TITLE
Relative links in rss feed

### ISSUE THREAD

**Issue by ckipp01** [npisanti/npisanti-nocms#1]
Hey Nicola! First of all, I really enjoy your site. Secondly, I'm in the process of building an rss reader that combines the rss feeds from the [webring](https://webring.xxiivv.com/) and I noticed that you're using relative links for images. So if someone is reading your rss feed, they won't find any of the images. You can see that [here](https://webring-checker.now.sh/rss?format=html) if you scroll down a bit to some of your posts with images.

**Comment by npisanti** [comment]
i was wondering why did it wrong now that i saw the RSS feed, i should modify my build script a bit to implement absolute path for RSS and relative for the site, relative are useful for me as i can build it on my machine and test it without having internet access

(or i should default everything to absolute and deal with modifying the script later, it could be a quicker fix)

**Comment by ckipp01** [comment]
Yea, I get what you mean. I was actually looking at your script to come up with a good solution, and I haven't thought of one that isn't 2 steps. Like setting a flag for local build vs production build to set them either relatively or absolute.

**Comment by npisanti** [comment]
ahahahah my script was nice at start but now is a TOTAL MESS, i should refactor it using bash functions

for the moment i will default to absolute, it won't take too much time to substitute my website main address with something al `LINKBASEPLACEHOLDER` to be sobstituted with `sed` in the script later

i just edited the latest posts for testing, i will do some and then finish it later (i'm thinking about using the journal as index page).

( i use the script for generating my website also as an exercise for learning bash scripting )

**Comment by ckipp01** [comment]
Sounds good!
